const citiesList = [
  "Hà Giang",
  "Cao Bằng",
  "Lào Cai",
  "Sơn La",
  "Lai Châu",
  "Bắc Kạn",
  "Lạng Sơn",
  "Tuyên Quang",
  "Yên Bái",
  "Thái Nguyên",
  "Điện Biên",
  "Phú Thọ",
  "Vĩnh Phúc",
  "Bắc Giang",
  "Bắc Ninh",
  "Hà Nội",
  "Quảng Ninh",
  "Hải Dương",
  "Hải Phòng",
  "Hòa Bình",
  "Hưng Yên",
  "Hà Nam",
  "Thái Bình",
  "Nam Định",
  "Ninh Bình",
  "Thanh Hóa",
  "Nghệ An",
  "Hà Tĩnh",
  "Quảng Bình",
  "Quảng Trị",
  "Thừa Thiên Huế",
  "Đà Nẵng",
  "Quảng Nam",
  "Quảng Ngãi",
  "Kon Tum",
  "Gia Lai",
  "Bình Định",
  "Phú Yên",
  "Đắk Lắk",
  "Khánh Hòa",
  "Đắk Nông",
  "Lâm Đồng",
  "Ninh Thuận",
  "Bình Phước",
  "Tây Ninh",
  "Bình Dương",
  "Đồng Nai",
  "Bình Thuận",
  "Hồ Chí Minh",
  "Long An",
  "Bà Rịa Vũng Tàu",
  "Đồng Tháp",
  "An Giang",
  "Tiền Giang",
  "Vĩnh Long",
  "Bến Tre",
  "Cần Thơ",
  "Kiên Giang",
  "Trà Vinh",
  "Hậu Giang",
  "Sóc Trăng",
  "Bạc Liêu",
  "Cà Mau",
];

export { citiesList };
